import "./globals.css";
import { Poppins } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faQ } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
import { faJournalWhills } from "@fortawesome/free-solid-svg-icons";
config.autoAddCss = false;
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-mauve1 flex flex-col  min-h-screen w-full text-mauve12`}
      >
        <header className="flex justify-end p-4">
          <div className="flex gap-4">
            <Link
              className="rounded-lg flex justify-center items-center text-center px-3 py-1.5  border border-mauve4 bg-mauve2 hover:border-mauve5 hover:bg-mauve3"
              href={"/sign-in"}
            >
              Sign in
            </Link>
            <Link
              className="rounded-lg flex justify-center items-center text-center px-4 py-1.5  border border-mauve11 hover:bg-mauve12 hover:text-mauve1"
              href={"/sign-up"}
            >
              Sign up
            </Link>
          </div>
        </header>
        <main className="flex-1 flex h-full w-full">{children}</main>
      </body>
    </html>
  );
}
